FROM node:18-alpine AS base

WORKDIR /app
COPY package*.json ./

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

FROM base AS development

RUN npm install
COPY . .
CMD ["npm", "run", "dev"]

FROM base AS build

COPY . .
RUN npm install
RUN npm run build

FROM node:18-alpine AS production

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app ./
RUN npm install --omit=dev

EXPOSE 3000
CMD ["npm", "start"]
